version: "2"

run:
  go: "1.25.9"

linters:
  default: none
  enable:
    - bodyclose
    - govet
    - ineffassign
    - nolintlint
  settings:
    govet:
      disable:
        - inline

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-same-issues: 50
