package v2

import proto "github.com/cosmos/gogoproto/proto"

// Wire schema provenance:
//   - tag: github.com/cosmos/ibc-go/v11 v11.2.0
//   - source: https://github.com/cosmos/ibc-go/blob/v11.2.0/proto/ibc/core/channel/v2/packet.proto
//   - source SHA-256: 3f74f5b89e53fb05777f13249fb9750c3c14deabf6126d1355ddc272b228d860
//   - upstream license: Apache-2.0
//
// These private types use the field numbers and wire types generated by
// protoc-gen-gogo for that exact schema. Keeping only this wire contract avoids
// importing the v11 types package, which also compiles SDK-dependent files.

type wirePacket struct {
	Sequence          uint64         `protobuf:"varint,1,opt,name=sequence,proto3"`
	SourceClient      string         `protobuf:"bytes,2,opt,name=source_client,json=sourceClient,proto3"`
	DestinationClient string         `protobuf:"bytes,3,opt,name=destination_client,json=destinationClient,proto3"`
	TimeoutTimestamp  uint64         `protobuf:"varint,4,opt,name=timeout_timestamp,json=timeoutTimestamp,proto3"`
	Payloads          []*wirePayload `protobuf:"bytes,5,rep,name=payloads,proto3"`
}

func (packet *wirePacket) Reset()         { *packet = wirePacket{} }
func (packet *wirePacket) String() string { return proto.CompactTextString(packet) }
func (*wirePacket) ProtoMessage()         {}

type wirePayload struct {
	SourcePort      string `protobuf:"bytes,1,opt,name=source_port,json=sourcePort,proto3"`
	DestinationPort string `protobuf:"bytes,2,opt,name=destination_port,json=destinationPort,proto3"`
	Version         string `protobuf:"bytes,3,opt,name=version,proto3"`
	Encoding        string `protobuf:"bytes,4,opt,name=encoding,proto3"`
	Value           []byte `protobuf:"bytes,5,opt,name=value,proto3"`
}

func (payload *wirePayload) Reset()         { *payload = wirePayload{} }
func (payload *wirePayload) String() string { return proto.CompactTextString(payload) }
func (*wirePayload) ProtoMessage()          {}

type wireAcknowledgement struct {
	AppAcknowledgements [][]byte `protobuf:"bytes,1,rep,name=app_acknowledgements,json=appAcknowledgements,proto3"`
}

func (ack *wireAcknowledgement) Reset()         { *ack = wireAcknowledgement{} }
func (ack *wireAcknowledgement) String() string { return proto.CompactTextString(ack) }
func (*wireAcknowledgement) ProtoMessage()      {}
