name: BUILD - build and binary upload

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      # checkout relayer before setup-go reads .go-version
      - name: checkout relayer
        uses: actions/checkout@v4

      # Install and setup go
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: '.go-version'

      # setup gopath
      - name: Set PATH
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash

      - name: run lint
        run: make lint

      # unit tests
      - name: run unit tests
        run: make test

      # build binary
      - name: build binary and move to upload location
        run: make build

      # upload resulting binaries
      - name: upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: rly
          path: ./build/rly
